---
title: "FinalBioCompRProject"
author: "Sarah Nicholls"
date: "11/29/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r libraries}
library(tidyverse)
library(dplyr)
library(readr)
library(stringr)
library(ggplot2)
```

## Converting .txt to .csv

```{r pressure, echo=FALSE}

##Function to convert .txt to .csv
txt_to_csv <- function(Directory){
  setwd(Directory)
  FILES <- list.files( pattern = ".txt")
  for (i in 1:length(FILES)){
    FILE=read.table(file=FILES[i],header=T,sep="")
    write.table(FILE,file=paste0(sub(".txt","",FILES[i]),".csv"),row.names=F,quote=F,sep=",")
  }
}
```


##combineing .csv functions
```{r}
##combining .csv functions
combining_csv <- function(directory1,directory2,newfilename){
  newfilename <- list.files(path=directory1, full.names = TRUE) %>% 
  lapply(read_csv) %>% 
  bind_rows
  answer <- readline("Would you like to 1.remove rows with NA’s in any
columns, 2. include NAs in the compiled data but be warned of their presence, or 3. include NAs in the
compiled data without a warning. Please input 1,2,or 3 to indicate your choice.")
  if(answer == "1"){
    newfilename <- na.omit(newfilename)
  }
  if(answer == "2"){
    print("these rows contain NA observations: ")
    print(is.na(newfilename))
  }
  newfilename$dayofYear <- 120
  if(newfilename == "countryX"){
    newfilename$country <- X
  }
  if(newfilename == "countryY"){
    newfilename$country <- Y
  }
  write.csv(newfilename, directory2, row.names = FALSE)
  txt_to_csv(directory2)
}
```


```{r summarize_function}
summarize_function <- function(data_given){
setwd("~Desktop/RProject2021")
data <- read_csv(data_given)

##obtaining male and female counts
  female_count <- sum(data$gender=="female")
  percent_female = female_count/length(data$gender)
  percent_male = 1-percent_female

  print("Percent Female: ")
  print(percent_female)
  print("Percent Male: ")
  print(percent_male)

##age distribution
  ggplot(data = data, aes(x=data$age)) + geom_histogram() + xlim(0,100) + labs(x= "Age", y = "count", title = "Age Distribution")
  
##infection rate 
  count_infection = 0
  data_marker <- data[,3:12]
  
  for(i in 1:nrow(data_marker)){
    for(j in range(1,10)){
      if(data_marker[i,j] == "1"){
        count_infection = count_infection + 1
        break
      }
    }
  }
infection_rate = count_infection/nrow(data_marker)
print("the infection rate is: ")
print(infection_rate)


##number of screens run

print("the number of screens run is: ")
print(nrow(data_marker)*ncol(data_marker))
}
```


Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
